### PR TITLE
support tree/ftree commands

### PR DESCRIPTION
**Pull request by mackong**
Support tree command to easily show an overview of a node.

tree             |  ftree
:-------------------------:|:-------------------------:
  |

### CODE REVIEW

**Comment by brouberol** [comment]
Thanks for contributing! The feature looks great :)

Would you mind rebasing your branch on top of `master` (I took this opportunity to revamp the dev environment) and fix the `tests/test_runner.py::test_help_general` test?

After that, we'll be good to go, and I'll release a new version. 

Thanks again!

**Comment by brouberol** [comment]
Travis seems to be _very_ slow to run and then report test cases. 

Everything runs OK locally, so I'm 👍 on this patch. Thanks again!

**Comment by mackong** [comment]
ok

**Comment by brouberol** [comment]
`izk` 0.4.4 has now been published to PyPI, which includes your patch!

**Pull request merged**
